language: julia
julia:
  - release
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -y gfortran
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@nomail.net"
  - cd ..; git clone --depth 1 git://github.com/abelsiqueira/cutest-julia-installer.git
  - cd cutest-julia-installer && ./download-cutest && ./install-cutest.sh
  - cd ../CUTEst.jl
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("CUTEst")'
  - LD_LIBRARY_PATH=. julia -e test/runtests.jl
