language: julia
julia:
  - release
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -y gfortran
  - git clone --depth 1 https://github.com/abelsiqueira/cutest-julia-install.git
  - cd cutest-julia-install && ./download-cutest && ./install-cutest.sh
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("CUTEst"); Pkg.test("CUTEst")'
