language: julia
os:
  - linux
  - osx
julia:
  - release
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get update -qq -y; else brew update; fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get install -y gfortran; else brew tap homebrew/science; fi
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@nomail.net"
  - cd ..; git clone --depth 1 git://github.com/abelsiqueira/cutest-julia-installer.git
  - cd cutest-julia-installer && ./download-cutest.sh && ./install-cutest.sh
  - cd ../CUTEst.jl
  - if [ $TRAVIS_OS_NAME == "linux" ]; then sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/4.6/libgfortran.so /usr/lib/; fi
script:
  - source ../cutest-julia-installer/cutest_variables
  - julia -e 'Pkg.clone(pwd()); Pkg.build("CUTEst"); Pkg.test("CUTEst", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("CUTEst")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
