language: julia
julia:
  - release
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -y gfortran
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@nomail.net"
  - cd ..; git clone --depth 1 git://github.com/abelsiqueira/cutest-julia-installer.git
  - cd cutest-julia-installer && ./download-cutest.sh && ./install-cutest.sh
  - cd ../CUTEst.jl
  - sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/4.6/libgfortran.so /usr/lib/
script:
  - source ../cutest-julia-installer/cutest_variables
  - julia -e 'Pkg.clone(pwd()); Pkg.build("CUTEst"); Pkg.test("CUTEst")'
